@startuml

title __MODEL's Class Diagram__\n

  namespace com.example.healthydiet {
    namespace Model {
      class com.example.healthydiet.Model.Article {
          - author : String
          - description : String
          - publishedAt : String
          - title : String
          - url : String
          - urlToImage : String
          + getAuthor()
          + getDescription()
          + getPublishedAt()
          + getSource()
          + getTitle()
          + getUrl()
          + getUrlToImage()
          + setAuthor()
          + setDescription()
          + setPublishedAt()
          + setSource()
          + setTitle()
          + setUrl()
          + setUrlToImage()
      }
    }
  }
  

  namespace com.example.healthydiet {
    namespace Model {
      class com.example.healthydiet.Model.Headlines {
          - articles : List<Article>
          - status : String
          - totalResults : String
          + getArticles()
          + getStatus()
          + getTotalResults()
          + setArticles()
          + setStatus()
          + setTotalResults()
      }
    }
  }
  

  namespace com.example.healthydiet {
    namespace Model {
      class com.example.healthydiet.Model.News {
          - articles : List<Article>
          - status : String
          - totalResults : int
          + getArticles()
          + getStatus()
          + getTotalResults()
          + setArticles()
          + setStatus()
          + setTotalResults()
      }
    }
  }
  

  namespace com.example.healthydiet {
    namespace Model {
      class com.example.healthydiet.Model.Source {
          - id : String
          - name : String
          + getId()
          + getName()
          + setId()
          + setName()
      }
    }
  }
  

  com.example.healthydiet.Model.Article o-- com.example.healthydiet.Model.Source : source


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
